"""
Method 10b: SAM-Med2D (Bonus)
Medical-tuned version of SAM via HuggingFace Transformers.

Requires: pip install transformers torch
"""

import numpy as np
import cv2
import torch
from typing import List, Dict
import sys
import os

try:
    from transformers import SamModel, SamProcessor
    HF_AVAILABLE = True
except ImportError:
    HF_AVAILABLE = False

sys.path.append(os.path.dirname(__file__))
from utils import post_process_mask


def generate_masks(
    image: np.ndarray,
    boxes: List[List[int]],
    config: Dict
) -> List[np.ndarray]:
    """
    Generate binary masks using HuggingFace's implementation of SAM.
    
    Args:
        image: Input image (HxWx3 RGB or HxW grayscale)
        boxes: List of bounding boxes [[x1,y1,x2,y2], ...]
        config: Configuration dictionary
                - 'model_id': HuggingFace model ID (default: "uni-medical/SAM-Med2D")
                - 'device': "cuda" or "cpu" (default: auto-detect)
    
    Returns:
        List of binary masks (HxW uint8, values 0 or 1), one per box
    """
    img_h, img_w = image.shape[:2]
    masks = []
    
    if not boxes:
        return masks

    model_id = config.get('model_id', 'uni-medical/SAM-Med2D')
    device = config.get('device', 'cuda' if torch.cuda.is_available() else 'cpu')
    
    if len(image.shape) == 2:
        img_rgb = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
    else:
        img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    try:
        if not HF_AVAILABLE:
            raise ImportError("transformers library is not installed.")
        
        # Load model and processor (Cached automatically by HF)
        processor = SamProcessor.from_pretrained(model_id)
        model = SamModel.from_pretrained(model_id).to(device)
        
        # Transformers expects a nested list of boxes per image: [[[x1, y1, x2, y2], ...]]
        input_boxes = [[boxes]] 
        
        # Prepare inputs
        inputs = processor(
            img_rgb, 
            input_boxes=input_boxes, 
            return_tensors="pt"
        ).to(device)

        # Forward pass
        with torch.no_grad():
            outputs = model(**inputs)
            
        # The output masks are of shape (batch_size, num_boxes, num_masks, H, W)
        # We take the mask with the highest IoU score (index 0 usually, but let's be safe)
        predicted_masks = outputs.pred_masks.squeeze(0) # Shape: (num_boxes, 3, H, W)
        
        # Iterate over each box's prediction
        for i in range(len(boxes)):
            # Pick the highest confidence mask out of the 3 generated by SAM
            best_mask_idx = outputs.iou_scores[0, i].argmax()
            
            # Convert to numpy and threshold at 0 (logits > 0)
            mask_tensor = predicted_masks[i, best_mask_idx]
            binary_mask = (mask_tensor.cpu().numpy() > 0).astype(np.uint8)
            
            # Post-processing
            binary_mask = post_process_mask(binary_mask, morphology_size=1)
            masks.append(binary_mask)

    except Exception as e:
        print(f"SAM-Med2D failed ({e}). Returning empty masks.")
        # Simpler fallback for the bonus method to save execution time
        for box in boxes:
            masks.append(np.zeros((img_h, img_w), dtype=np.uint8))

    return masks


if __name__ == "__main__":
    print("Testing SAM-Med2D method (Initialization check)...")
    test_image = np.random.randint(0, 255, (256, 256, 3), dtype=np.uint8)
    test_boxes = [[10, 10, 50, 50], [60, 60, 90, 90]]
    test_config = {'model_id': 'facebook/sam-vit-base', 'device': 'cpu'} # Use base for fast test
    
    # Warning: Without the transformers library installed, this triggers the fallback.
    masks = generate_masks(test_image, test_boxes, test_config)
    print(f"Generated {len(masks)} masks")
    print("✓ SAM-Med2D pipeline test completed")